packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
allowBuilds:
  esbuild: set this to true or false
  simple-git-hooks: set this to true or false
minimumReleaseAgeExclude:
  - vite@8.1.0
